schemaVersion: 2.2.0

components:
  - name: announcements-image
    image:
      dockerfile:
        uri: ./Containerfile
        buildContext: .
      imageName: announcements-image
 
  - name: announcements
    container:
      image: announcements-image
      endpoints:
      - name: http-8000
        targetPort: 8000
    attributes:
      container-overrides:
        imagePullPolicy: IfNotPresent 
