FROM mysql:latest

COPY ./my.cnf /etc/mysql/conf.d/
COPY ./database/set_innodb.sql /docker-entrypoint-initdb.d/

RUN chmod 777 /var/run/mysqld
RUN chmod 777 /var/lib/mysql

COPY ./database/announcements.sql /database.sql
