version: '3'
services:
  db:
    build:
      dockerfile: ./Containerfile-database
    ports:
      - 3306
    env_file:
      - ./.env
    volumes:
      - ~/temp/mysqld:/var/run/mysqld:rw
      - ~/temp/db:/var/lib/mysql:rw
  web:
    build: 
      dockerfile: ./Containerfile
    ports:
      - "8004:8004"
    volumes:
      - ~/temp/mysqld:/var/run/mysqld:rw
    depends_on:
      - db

