version: '3'
services:
  db:
    build:
      dockerfile: ./Containerfile-db
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    volumes:
      - ~/temp/mysqld:/var/run/mysqld:rw
      - ~/temp/db:/var/lib/mysql:rw
  web:
    build: 
      dockerfile: ./Containerfile-web
    ports:
      - "8004:8000"
    volumes:
      - ~/temp/mysqld:/var/run/mysqld:Z
    depends_on:
      - db

