version: '2'
services:
  db:
    build:
      dockerfile: ./Containerfile-db
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:3306"]
      interval: 10s
      timeout: 10s
      retries: 5

  web:
    build: 
      dockerfile: ./Containerfile-web
    ports:
      - "8004:8000"
    depends_on:
      db:
        condition: service_healthy

