# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20170503_1333'),
    ]

    operations = [
        migrations.AlterField(
            modal_name='revision',
            name='announcement',
            field=models.IntegerField(default=0)
        ),
        migrations.RemoveField(
            model_name='revision',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='announcement_ptr',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='previous',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
