# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20170503_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
