# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 18:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_profile_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
