# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-22 15:05
from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20170830_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
