# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2024-11-13 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_collation_charsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='emoji',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
