# Generated by Django 4.2.16 on 2024-11-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_alter_announcement_id_alter_audience_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='emoji',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
